from typing import Any, Dict, Optional
from agents.common.base import BaseAgent
from agents.common.client import AegisMeshClient


class ExecutorAgent(BaseAgent):
    """
    Executor agent responsible for artifact compilation and action execution.
    Protected tool actions are guarded by PEP before execution.
    """

    def __init__(
        self,
        agent_id: str = "executor-01",
        name: str = "Task Executor",
        client: Optional[AegisMeshClient] = None,
    ):
        super().__init__(
            agent_id=agent_id,
            name=name,
            role="executor",
            capabilities=["report.generate", "fs.read", "fs.write"],
            metadata={"priority": "high", "domain": "execution"},
            client=client,
        )

    # -----------------------------------------------------------------------
    # Tool Execution Implementations (Actual Tools)
    # -----------------------------------------------------------------------

    def _exec_generate_report(
        self,
        title: str,
        template: str = "executive_briefing",
    ) -> Dict[str, Any]:
        """Underlying tool execution for report generation."""
        return {
            "title": title,
            "template": template,
            "format": "markdown",
            "status": "generated",
            "content": f"# {title}\n\nGenerated by AegisMesh Executor Agent under runtime integrity enforcement.",
        }

    def _exec_fs_write(self, path: str, content: str) -> Dict[str, Any]:
        """Underlying tool execution for filesystem write (high-risk)."""
        return {
            "path": path,
            "bytes_written": len(content),
            "status": "written",
        }

    # -----------------------------------------------------------------------
    # Protected Tool Methods (Guarded by PEP)
    # -----------------------------------------------------------------------

    async def execute_generate_report(
        self,
        title: str,
        template: str = "executive_briefing",
        session_id: Optional[str] = "session-001",
        mission_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Executes report.generate protected by PEP guard.
        ALLOW -> executes tool and returns generated report.
        """
        payload = {"title": title, "template": template}
        decision = await self.guard(
            action="report.generate",
            payload=payload,
            session_id=session_id,
            mission_id=mission_id,
        )
        return self._exec_generate_report(title=title, template=template)

    async def execute_fs_write(
        self,
        path: str,
        content: str,
        session_id: Optional[str] = "session-001",
        mission_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Attempts fs.write protected by PEP guard.
        Should be BLOCKED because fs.write is classified as high-risk.
        """
        payload = {"path": path, "content": content}
        decision = await self.guard(
            action="fs.write",
            payload=payload,
            session_id=session_id,
            mission_id=mission_id,
        )
        return self._exec_fs_write(path=path, content=content)

    # -----------------------------------------------------------------------
    # Event Emission / Foundation Workflow
    # -----------------------------------------------------------------------

    async def generate_report(
        self,
        title: str,
        template: str = "executive_briefing",
        session_id: Optional[str] = "session-001",
    ) -> Dict[str, Any]:
        """
        Emits tool_call_request for report.generate to AegisMesh.
        """
        payload = {
            "tool": "report.generate",
            "title": title,
            "template": template,
            "agent": self.agent_id,
            "output_format": "markdown",
        }
        return await self.emit_event(
            event_type="tool_call_request",
            action="report.generate",
            payload=payload,
            session_id=session_id,
        )

    async def run_step(self, session_id: Optional[str] = "session-001", **kwargs) -> Dict[str, Any]:
        """
        Generates standard test report compilation event.
        """
        title = kwargs.get("title", "AegisMesh Autonomous Integrity Assessment")
        template = kwargs.get("template", "executive_briefing")
        return await self.generate_report(title=title, template=template, session_id=session_id)
