import type { FigmaAgent as Agent, ReplayEvent, RuntimeEvent } from "./types/figma";

export const mission =
  "Research Redis caching strategies and produce a verified report"

export const agents: Agent[] = [
  {
    id: "planner-01",
    name: "Planner-01",
    role: "Orchestrator",
    status: "Active",
    trust: 97,
    tier: "Trusted",
    mission,
    step: "Monitor delegated execution",
    lastEvent: "4 sec ago",
    contract: "v1.4 · 62f0…a12c",
    token: "Expires in 11m",
    capabilities: ["plan.create", "task.delegate", "session.read"],
    dimensions: {
      Compliance: 98,
      Integrity: 100,
      Consistency: 96,
      "Claim accuracy": 94,
    },
  },
  {
    id: "researcher-01",
    name: "Researcher-01",
    role: "Intelligence",
    status: "Quarantined",
    trust: 34,
    tier: "Quarantined",
    mission,
    step: "Step 02 · Research caching strategies",
    lastEvent: "19 sec ago",
    contract: "v1.8 · a81d…49f2",
    token: "Revoked",
    capabilities: ["web.search", "web.read", "research_db.read"],
    dimensions: {
      Compliance: 42,
      Integrity: 18,
      Consistency: 76,
      "Claim accuracy": 100,
    },
  },
  {
    id: "executor-01",
    name: "Executor-01",
    role: "Operations",
    status: "Active",
    trust: 96,
    tier: "Trusted",
    mission,
    step: "Step 03 · Generate verified report",
    lastEvent: "7 sec ago",
    contract: "v1.3 · 8c21…f90d",
    token: "Expires in 8m",
    capabilities: ["report.generate", "fs.read", "fs.write"],
    dimensions: {
      Compliance: 98,
      Integrity: 97,
      Consistency: 95,
      "Claim accuracy": 96,
    },
  },
]

export const runtimeEvents: RuntimeEvent[] = [
  {
    seq: 18402,
    time: "10:31:07.102",
    agent: "Planner-01",
    type: "Task reassigned",
    resource: "plan.step_02",
    decision: "Allow",
    severity: "Low",
    latency: 18,
    reason: "Workflow continuity obligation completed",
    hash: "a81d782e304b6a9c49f2",
    previousHash: "39bc501e6d910e7a10ea",
    signature: "Verified",
  },
  {
    seq: 18401,
    time: "10:31:06.940",
    agent: "Researcher-01",
    type: "Agent quarantined",
    resource: "enforcement.quarantine",
    decision: "Block",
    severity: "Critical",
    latency: 19,
    reason: "Critical mission violation after untrusted-content trigger",
    hash: "39bc501e6d910e7a10ea",
    previousHash: "71ff38ac920172d4c903",
    signature: "Verified",
  },
  {
    seq: 18400,
    time: "10:31:06.936",
    agent: "Researcher-01",
    type: "Capability revoked",
    resource: "token jti_7a92",
    decision: "Block",
    severity: "Critical",
    latency: 15,
    reason: "Quarantine obligation",
    hash: "71ff38ac920172d4c903",
    previousHash: "022a9c72f19320aff92d",
    signature: "Verified",
  },
  {
    seq: 18399,
    time: "10:31:06.921",
    agent: "Researcher-01",
    type: "Tool request denied",
    resource: "database.export",
    decision: "Block",
    severity: "Critical",
    latency: 12,
    reason: "MISSION_VIOLATION · alignment 0.02",
    hash: "022a9c72f19320aff92d",
    previousHash: "9d10bb228cbb0a21b8c2",
    signature: "Verified",
  },
  {
    seq: 18398,
    time: "10:31:06.904",
    agent: "Researcher-01",
    type: "Injection detected",
    resource: "docs.cache-patterns.net",
    decision: "Sandbox",
    severity: "High",
    latency: 31,
    reason: "Instruction-like content from untrusted source",
    hash: "9d10bb228cbb0a21b8c2",
    previousHash: "c3403aa2019f2c8172da",
    signature: "Verified",
  },
  {
    seq: 18397,
    time: "10:31:05.122",
    agent: "Researcher-01",
    type: "Web document read",
    resource: "web.read",
    decision: "Allow",
    severity: "Low",
    latency: 42,
    reason: "Allowed by current plan step",
    hash: "c3403aa2019f2c8172da",
    previousHash: "b37fc100134add1f3e19",
    signature: "Verified",
  },
  {
    seq: 18396,
    time: "10:31:04.618",
    agent: "Planner-01",
    type: "Step delegated",
    resource: "Researcher-01",
    decision: "Allow",
    severity: "Low",
    latency: 9,
    reason: "Effective permissions verified",
    hash: "b37fc100134add1f3e19",
    previousHash: "4d902fc0a118ef291447",
    signature: "Verified",
  },
  {
    seq: 18395,
    time: "10:31:03.401",
    agent: "Executor-01",
    type: "Snapshot created",
    resource: "workspace/report",
    decision: "Allow",
    severity: "Low",
    latency: 37,
    reason: "Pre-write snapshot obligation",
    hash: "4d902fc0a118ef291447",
    previousHash: "f8aa222147cf641a1210",
    signature: "Verified",
  },
]

export const replayEvents: ReplayEvent[] = [
  {
    time: "10:31:01.014",
    title: "Session established",
    description: "Agent identities and capability tokens verified.",
    agent: "Planner-01",
    trustBefore: 97,
    trustAfter: 97,
    state: "Active",
    policy: "identity@v1.4",
  },
  {
    time: "10:31:03.102",
    title: "Plan declared",
    description: "Three-step plan compiled against active mission contracts.",
    agent: "Planner-01",
    trustBefore: 97,
    trustAfter: 97,
    state: "Active",
    policy: "plan-verifier@v2.1",
  },
  {
    time: "10:31:04.618",
    title: "Research delegated",
    description: "Step 02 delegated with intersected permissions.",
    agent: "Researcher-01",
    trustBefore: 94,
    trustAfter: 94,
    state: "Active",
    policy: "delegation@v1.7",
  },
  {
    time: "10:31:05.122",
    title: "Untrusted content read",
    description:
      "External document labelled untrusted and provenance recorded.",
    agent: "Researcher-01",
    trustBefore: 94,
    trustAfter: 94,
    state: "Active",
    policy: "provenance@v1.3",
  },
  {
    time: "10:31:06.904",
    title: "Injection pattern detected",
    description:
      "Retrieved content contained an instruction override and extraction request.",
    agent: "Researcher-01",
    trustBefore: 94,
    trustAfter: 79,
    state: "Degraded",
    policy: "content-safety@v2.2",
  },
  {
    time: "10:31:06.921",
    title: "Data export denied",
    description:
      'database.export("customers") was outside the mission and active plan.',
    agent: "Researcher-01",
    trustBefore: 79,
    trustAfter: 34,
    state: "Halted",
    policy: "mission-integrity@v1.8",
  },
  {
    time: "10:31:06.940",
    title: "Agent quarantined",
    description: "Token revoked, agent isolated, and evidence checkpointed.",
    agent: "Researcher-01",
    trustBefore: 34,
    trustAfter: 34,
    state: "Quarantined",
    policy: "enforcement@v1.6",
  },
  {
    time: "10:31:07.102",
    title: "Workflow recovered",
    description:
      "Remaining plan reassigned while Planner-01 and Executor-01 continued.",
    agent: "Planner-01",
    trustBefore: 97,
    trustAfter: 97,
    state: "Active",
    policy: "continuity@v1.2",
  },
]
